services:
  db:
    image: postgres:16
    container_name: loan_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loan_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: loan_api
    ports:
      - "5000:5000"
    env_file:
      - .env.${FLASK_ENV:-dev}
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/loan_db
    depends_on:
      - db

volumes:
  pgdata:
